# Generated by Django 2.2 on 2020-05-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200501_0241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='booking',
        ),
    ]
